POST http://127.0.0.1:3000/api/v2/product
Content-Type: application/json

{
  "productName": "Oversize T-Shirt",
  "productDesc": "Cotton 100%",
  "price": 590,
  "sizes": [
    { "size": "S", "stock": 10 },
    { "size": "M", "stock": 0 },
    { "size": "L", "price": 650, "stock": 5 }
  ]
}